### ISSUE TITLE
After New Updates From Telegram Forwarding Not Working

### ISSUE THREAD

**Issue by Asnkbth** [aahnik/tgcf#328]

**Comment by tissole** [comment]
Update telethon to the latest version.

**Comment by berkinalex** [comment]
I confirm the error, I have tried to update the libraries but something must escape me...
<img width="824" alt="error" src="https://user-images.githubusercontent.com/2515744/144723271-969106a1-2a62-4425-8ec3-4227cba543c2.png">

**Comment by jerung3000** [comment]
still not working..only working with the old telegram..

**Comment by jerung3000** [comment]
still not working
![error telethon](https://user-images.githubusercontent.com/82352663/144779827-721d60a6-4389-4242-9910-92a8c807d86a.png)
..

**Comment by jerung3000** [comment]
> still not working ![error telethon](https://user-images.githubusercontent.com/82352663/144779827-721d60a6-4389-4242-9910-92a8c807d86a.png) ..

Done, just update your puthon and telethon for this issue..
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade telethon

or

python -m pip install --upgrade pip
python -m pip install --upgrade telethon

**Comment by fiRinhozor** [comment]
What about the new update that came yesterday for Telegram where creators of the channel have an option for restricting forwarding? Can anybody test if it works, please? Thanks

**Comment by simonlkch** [comment]
> What about the new update that came yesterday for Telegram where creators of the channel have an option for restricting forwarding? Can anybody test if it works, please? Thanks Telegram Update Information: Protected Content in Groups and Channels • Content creators can restrict the ability to forward messages from their groups and channels. • When forwarding is restricted, users will also be unable to directly save media from the chat or take screenshots. • Toggle this option on or off via Chat Info > Group / Channel Type.

after the telegram have update the Protected Content
tgcf can't forward message the group/channel are set to protected.

**Comment by tazboys** [comment]
is the case even "show_forwarded_from: false" ?

**Comment by Wandrius** [comment]
Hello, let's look for ways to solve this problem together, texts are still being shared but images are not, the cache should be saved somewhere on the computer with encryption that I still can't imagine, I'm looking in Russian forums to see if I can find something, I use this tool in my work, to channel information but some private channels have restricted the content.

Let's look for a solution to this big problem together.

https://t.me/wandrius

**Comment by denpasare** [comment]
yes not working after the update and the new version of telethon but there is a bot that can do that the bot is named junction her is the website junction.space

**Comment by azlk** [comment]
> yes not working after the update and the new version of telethon but there is a bot that can do that the bot is named junction her is the website junction.space

it's not free absolutely!

**Comment by denpasare** [comment]
euh yes and the other problem is that is detected in some channel and could be banned and you could lost your money
